services:

  s1:
    env_file:
      - server.env
    volumes:
      - ./data/s1:/var/lib/mysql
      - "./etc/mysql/my.cnf:/etc/my.cnf:ro"
      - "./etc/s1:/etc/my.cnf.d:ro"
      - "./initialize.js:/var/initialize.js:ro"
    image: container-registry.oracle.com/mysql/community-server:9.0.1
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--skip-name-resolve"]

  s2:
    volumes:
      - ./data/s2:/var/lib/mysql
      - "./etc/mysql/my.cnf:/etc/my.cnf:ro"
      - "./etc/s2:/etc/my.cnf.d:ro"
    env_file:
      - server.env
    image: container-registry.oracle.com/mysql/community-server:9.0.1
    command: ["mysqld","--server_id=2","--skip-name-resolve"]
    ports:
      - "3302:3306"
      
  s3:
    volumes:
      - ./data/s3:/var/lib/mysql
      - "./etc/mysql/my.cnf:/etc/my.cnf:ro"
      - "./etc/s3:/etc/my.cnf.d:ro"
    env_file:
      - server.env
    image: container-registry.oracle.com/mysql/community-server:9.0.1
    command: ["mysqld","--server_id=3","--skip-name-resolve"]
    ports:
      - "3303:3306"

  router:
    volumes:
      - ./etc/mysqlrouter/:/etc/mysqlrouter/
      - ./data/mysqlrouter/:/tmp/mysqlrouter/
    env_file:
      - router.env
    image: container-registry.oracle.com/mysql/community-router:9.0.1
    ports:
      - "6446:6446"
      - "6447:6447"
      - "6448:6448"
      - "6449:6449"
      - "8443:8443"
    depends_on:
      - s1
      - s2
      - s3
    restart: on-failure

